// app/(tabs)/LoginStyles.tsx
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffe5ec", // Modern solid background
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  // Glass morphism effect for form container
  formContainer: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 20,
    padding: 32,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 25,
    elevation: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  // Elegant header section
  headerContainer: {
    alignItems: "center",
    marginBottom: 40,
  },
  title: {
    fontSize: 32,
    fontWeight: "800",
    color: "#2c3e50",
    marginBottom: 8,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 16,
    color: "#7f8c8d",
    textAlign: "center",
    fontWeight: "400",
  },
  // Modern input styling
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#34495e",
    marginBottom: 8,
    marginLeft: 4,
  },
  input: {
    borderWidth: 2,
    borderColor: "#e8f4fd",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 16,
    width: "100%",
    backgroundColor: "#ffffff",
    fontSize: 16,
    color: "#2c3e50",
    shadowColor: "#3498db",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
    fontFamily: "System", // Use system font for better readability
  },
  inputFocused: {
    borderColor: "#3498db",
    shadowOpacity: 0.2,
    shadowRadius: 16,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#e8f4fd",
    borderRadius: 16,
    width: "100%",
    backgroundColor: "#ffffff",
    shadowColor: "#3498db",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation: 3,
  },
  passwordInput: {
    flex: 1,
    paddingVertical: 16,
    paddingHorizontal: 20,
    fontSize: 16,
    color: "#2c3e50",
  },
  eyeButton: {
    padding: 12,
    marginRight: 8,
    borderRadius: 8,
  },
  // Enhanced status messages
  correctText: {
    color: "#27ae60",
    alignSelf: "flex-start",
    marginTop: 8,
    marginBottom: 16,
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 4,
  },
  errorText: {
    color: "#e74c3c",
    alignSelf: "flex-start",
    marginTop: 8,
    marginBottom: 16,
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 4,
  },
  // Button styling with gradient effect
  buttonContainer: {
    width: "100%",
    marginTop: 24,
    gap: 16,
  },
  loginButton: {
    backgroundColor: "#ff8fab",
    paddingVertical: 18,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#3498db",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(52, 152, 219, 0.3)",
  },
  loginButtonPressed: {
    backgroundColor: "#2980b9",
    transform: [{ scale: 0.98 }],
  },
  loginButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  registerButton: {
    backgroundColor: "transparent",
    paddingVertical: 18,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "#bdc3c7",
    alignItems: "center",
    justifyContent: "center",
  },
  registerButtonPressed: {
    backgroundColor: "rgba(189, 195, 199, 0.1)",
    borderColor: "#95a5a6",
  },
  registerButtonText: {
    color: "#7f8c8d",
    fontSize: 16,
    fontWeight: "600",
  },
  // Enhanced loading state
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  loadingText: {
    marginLeft: 12,
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 16,
  },
  // Input validation states
  inputError: {
    borderColor: "#e74c3c",
    borderWidth: 2,
    shadowColor: "#e74c3c",
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  inputSuccess: {
    borderColor: "#27ae60",
    borderWidth: 2,
    shadowColor: "#27ae60",
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  // Modern decorative elements
  decorativeCircle1: {
    position: "absolute",
    top: -50,
    right: -50,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(52, 152, 219, 0.1)",
  },
  decorativeCircle2: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(155, 89, 182, 0.1)",
  },
  // Professional divider
  divider: {
    height: 1,
    backgroundColor: "rgba(127, 140, 141, 0.2)",
    marginVertical: 24,
    width: "100%",
  },
  dividerText: {
    position: "absolute",
    alignSelf: "center",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 16,
    color: "#95a5a6",
    fontSize: 14,
    fontWeight: "500",
    top: -10,
  },
  // Forgot password link
  forgotPasswordContainer: {
    alignItems: "center",
    marginTop: 20,
  },
  forgotPasswordText: {
    color: "#3498db",
    fontSize: 14,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  // Social login buttons (if needed)
  socialButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 24,
    gap: 12,
  },
  socialButton: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e8f4fd",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  socialButtonText: {
    color: "#7f8c8d",
    fontSize: 14,
    fontWeight: "600",
  },
});
