// app/(tabs)/RegisterPageStyles.tsx
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: "#F8F9FA", 
    justifyContent: "center", 
    alignItems: "center", 
    padding: 24 
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 32,
    width: "100%",
    maxWidth: 400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  backButton: {
    position: "absolute",
    top: 60,
    left: 20,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backButtonText: {
    color: "#007AFF",
    marginLeft: 6,
    fontSize: 16,
    fontWeight: "600",
  },
  header: {
    alignItems: "center",
    marginBottom: 30,
  },
  title: { 
    fontSize: 28, 
    fontWeight: "700", 
    marginBottom: 8,
    color: "#34495E",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: "#636E72",
    textAlign: "center",
  },
  formCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 32,
    width: "100%",
    maxWidth: 400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: "#34495E",
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  input: { 
    backgroundColor: "#F8F9FA",
    borderWidth: 1, 
    borderColor: "#E5E5EA", 
    padding: 14, 
    borderRadius: 16, 
    width: "100%", 
    fontSize: 16,
    color: "#2D3436",
  },
  passwordContainer: { 
    flexDirection: "row", 
    alignItems: "center", 
    backgroundColor: "#F8F9FA",
    borderWidth: 1, 
    borderColor: "#E5E5EA", 
    borderRadius: 16, 
    width: "100%", 
    paddingRight: 12,
  },
  passwordInput: { 
    flex: 1, 
    padding: 14,
    fontSize: 16,
    color: "#2D3436",
  },
  eyeButton: { 
    padding: 8,
    borderRadius: 6,
  },
  passwordHint: {
    fontSize: 12,
    color: "#F39C12",
    marginTop: 4,
    marginLeft: 4,
    fontWeight: "500",
  },
  passwordError: {
    fontSize: 12,
    color: "#E74C3C",
    marginTop: 4,
    marginLeft: 4,
    fontWeight: "500",
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 16,
    marginVertical: 12,
    gap: 8,
    borderLeftWidth: 4,
  },
  errorContainer: {
    backgroundColor: "#FDEDED",
    borderLeftColor: "#E74C3C",
  },
  successContainer: {
    backgroundColor: "#EAF7EE",
    borderLeftColor: "#27AE60",
  },
  statusText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "500",
    textAlign: "left",
  },
  errorText: {
    color: "#E74C3C",
  },
  successText: {
    color: "#27AE60",
  },
  registerButton: {
    backgroundColor: "#ff8fab",
    paddingVertical: 16,
    borderRadius: 16,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    marginTop: 8,
    flexDirection: "row",
    gap: 8,
    shadowColor: "#FF6B81",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 5,
  },
  registerButtonDisabled: {
    backgroundColor: "rgba(255, 107, 129, 0.5)",
  },
  registerButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
  termsText: {
    fontSize: 12,
    color: "#636E72",
    textAlign: "center",
    lineHeight: 16,
    marginBottom: 8,
  },
  loginLinkContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
  },
  loginText: {
    fontSize: 16,
    color: "#636E72",
    fontWeight: "400",
  },
  loginLink: {
    fontSize: 16,
    color: "#6C5CE7",
    fontWeight: "600",
    marginLeft: 6,
    textDecorationLine: "underline",
  },
  loginLinkDisabled: {
    color: "rgba(108, 92, 231, 0.5)",
  },
});